### ISSUE TITLE
Run error python3 RAASNet.py 

### ISSUE THREAD

**Issue by MarkBread** [leonv024/RAASNet#3]
i'm getting this error when i try to run te program

Traceback (most recent call last):
  File "RAASNet.py", line 50, in <module>
    from ttkthemes import ThemedStyle
ModuleNotFoundError: No module named 'ttkthemes'

i installed all requirements using :
pip install -r requirements.txt since pip3 install -r requirements.txt was not working.
can you help me ?
how do i fix this?

**Comment by leonv024** [comment]
pip and pip3 are not the same.

pip is for Python 2.7
pip3 is for Python 3.7

if you do " pip install -r requirements.txt", you install the requirements for python 2.7, but the scipt is Python 3.7.

Did you install python 3 properly? What OS you're on?

If you're on Windows, be sure to check the box that says: "Add python 3.7 to PATH" during the installation of Python 3. Otherwise pip3 won't work.

**Comment by SucketRansom** [comment]
In windows use only python not python3

**Comment by SucketRansom** [comment]
I mean write python RAASNET.py

**Comment by SucketRansom** [comment]
And you must install python 3
