### ISSUE TITLE
Can't unlock the files with key on target PC

### ISSUE THREAD

**Issue by TerryJLU** [leonv024/RAASNet#43]
Hi 
I think I tried to use Pycrypto and PyAES to get payload
But the key could unlock the files on local PC
If the payload is runned on target PC ,always failed to unlock files

https://drive.google.com/file/d/1fDiFxeZ7fw2HWGNfCIDQDNQRWFQcT734/view?usp=sharing

**Comment by leonv024** [comment]
Sounds new. There are various youtube videos where you can see that the decryptor is working and RAASNet was tested very well.

Note there is no other way to unlock the files. You have to use the decryptor with the correct key in order to recover the files.

Are there any errors in the terminal? Did you use the correct decryptor? PyAES decryptor cannot decrypt PyCrypto.

**Comment by TerryJLU** [comment]
Yes it is ok with Ghost Payload 
,Unlocked Pycrypto and PyAES payload files are failed on target PC

[ ERROR ] Incorrect AES key length (29 bytes)
![12123](https://user-images.githubusercontent.com/19278622/102678265-428ec800-41e2-11eb-8772-42063c9329f1.png)

the key is from attacker PC

**Comment by TerryJLU** [comment]
And I tried the key on onion dashboard shown

**Comment by leonv024** [comment]
Hi, the key shown is 29-bytes, which is a invalid length.

The key is a MD5 hash of a randomly generated string. I choose for using a MD5 hash because it always returns a 32-bytes string.

I see you're using a different language on your PC, which (apparently) results in encoding issues.

However, I it shouldn't even be your decryption key because if it can't decrypt files with a invalid key(-length) neither it can encrypt them with that same key.
