### ISSUE TITLE
Issue with the OTP file

### ISSUE THREAD

**Issue by KhorneDevilsWare** [leonv024/RAASNet#48]
I've run the OTP file and used google authenticator  to get the Auth code.
But the OTP button on the site is broken, so I can't set the onion server as the C&C.
Also might wanna add instructions on how to use the onion server as a C&C.

**Comment by leonv024** [comment]
I see you're confused on how RAASNet works. Let me clear things up so you understand.

OTP Button:
I'm aware the OTP button on the profile section of the onion site doesn't work. It was ment to setup OTP login for your account on the onion panel but it was a unfinished feature of the onion site.

If you've used the python script, you won't need it because you've already setup OTP.

How it works:
OTP is a test feature.
You can use the OTP code instead of your password to login to the onion site.

You still need your password to login to the RAASNet client. OTP login for the RAASNet client is a unfinished feature.

About Instructions:
I should make a Wiki page, indeed.

The onion site is straight forward. It serves as a storage location for your keys so you can reach them without needing to have access to the RAASNet server, in case you need them.

If your RAASNet server receives a key, it's also stored on the onion site, if it didn't receive it (for ex.: a firewall blocked it), the key is lost.

You can also delete your keys.

NOTE: If you delete a key from the onion site, it cannot be recovered. We do not mark it as "deleted" and hide it like a social media post. It's gone. The data you see is the data we have. You are in full control of your data.

**Comment by KhorneDevilsWare** [comment]
Thank you for clearing this up.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
