### ISSUE TITLE
Its cool and all but whats the purpose?

### ISSUE THREAD

**Issue by hackthedev** [leonv024/RAASNet#94]
I mean yeah "as a service". I really like the project but I cant think of any commercial method to use it. The only thing that comes in my mind is to use it for bad purposes or as a learning proejct.

Its just something in my opinion and feedback. Like i said: **It is really cool though!**

**Comment by leonv024** [comment]
There are multiple use cases.

There is a forum where someone recommended this payload as encryption service to keep their files secure. There are also people who use this project to test how to can prevent ransomware from encrypting their files by detecting various behaviour, such as the renaming process, which would happen on honey pot files first, the ransomware process gets killed, and your real files are safe.

People also use this project for Cyber Security courses.

But I made it for myself as Security demo/POC to encrypt a network of VM's, to demonstrate how important it is not to click on random shit, because that's what could happen. I didn't release the dropper, for obvious reasons.

Anyway, if you would've read the README or the FAQS on the C&C domain, you would've known why I made and released this.

But mainly, as you already said, its just a cool little project. :)
